name: Python CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy flake8 black isort

      - name: Check code formatting with Black
        # run: black --check src tests
        run: black --check src

      - name: Check import sorting with isort
        # run: isort --check-only src tests
        run: isort --check-only src

      - name: Run mypy
        run: mypy src

      - name: Run flake8
        # run: flake8 src tests
        run: flake8 src

    # - name: Run tests
    #   run: pytest tests

    # - name: Upload coverage reports to Codecov
    #   uses: codecov/codecov-action@v3
    #   env:
    #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
